### ISSUE TITLE
Firefox 55: g<Esc> = crash

### ISSUE THREAD

**Issue by congma** [willsALMANJ/pentadactyl-signed#4] opened 2017-08-25 04:33 UTC
Just to report a crash.

With Firefox 55.0.2, pentadactyl sort of works.  But when the key sequence <kbd>g</kbd><kbd>Esc</kbd> is pressed, Firefox immediately crashes.

**Comment by magnetophon** [comment] 2017-08-25 07:34
I can reproduce this, also on 55.0.2.

**Comment by wshanks** [comment] 2017-08-25 17:37
Hmm, okay. That seems hard to debug because of the crashing. I assume you are making sure that multiprocessing is turned off.

Have you tried in a fresh profile with multiprocessing disabled? 55 was a pretty bad experience for me to start out (freezing and crashing randomly). I created a new profile and installed only WebExtensions in it and Firefox has been running smoothly that way, so I think there might have been some changes that combine badly with XUL addons.

Post here if you find any other sequences that reliably crash Firefox.

I might be able to help some with figuring out what is going on, but I think it will require carefully stepping through in the debugger to figure out where the crash is, and it's hard for me to justify spending much time on it because I am pretty busy and I'd rather spend time on something else like finding a replacement for Pentadactyl that will work after version 56.

**Comment by congma** [comment] 2017-08-26 09:24
The crash is getting a bit ridiculous... This is another reliable crash for me: simply typing <kbd>Enter</kbd> in "Normal mode" (that is, not in an input field or something) will crash it.

Could anyone replicate this?

**Comment by magnetophon** [comment] 2017-08-27 06:53
@congma yup, I can reproduce the ``Enter`` crash.  :(

**Comment by jfl209** [comment] 2017-08-31 15:46
Are there any workarounds for the `Enter` and `g <Esc>` behaviors?

**Comment by upsuper** [comment] 2017-09-07 22:26
FYI, fix has landed in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1397711) but it is probably not very likely it would get to 55 given that it is near the end of this cycle. Maybe 56 can get it :/

**Comment by wshanks** [comment] 2017-09-08 03:34
Wow, nice work tracking down that bug. So is there no easy way to work around the bug in Pentadactyl in 55?

**Comment by upsuper** [comment] 2017-09-08 03:45
This crash wouldn't happen if you don't pass `KeyboardEvent` created from script to `dispatchDOMEventViaPresShell`. I don't know if it is possible to avoid for you, though.

**Comment by wshanks** [comment] 2017-09-08 04:37
It seems like the only usage is at https://github.com/5digits/dactyl/blob/31a6ba0bcbf92bb393a529bde78610ee2297b55c/common/modules/dom.jsm#L1484 I wonder how bad it would be to take out that conditional and just do `target.dispatchEvent(event)` instead.

Also, noting that this issue seems to be the same as https://github.com/5digits/dactyl/issues/216

**Comment by wshanks** [comment] 2017-09-14 13:18
Okay, well, I just did some quick testing with Firefox 56 beta and the current Pentadactyl xpi doesn't crash for me there, so I'm going to close this. I don't think it's worth putting a workaround in just for 55.

**Closed as completed by wshanks** 2017-09-14 13:18 UTC
